<?php

declare(strict_types=1);

namespace Spatial\Console\Commands;

use Spatial\Console\AbstractCommand;
use Spatial\Console\Application;

/**
 * Config Cache Command
 * 
 * Caches all configuration files for production.
 * 
 * @example php spatial config:cache
 * 
 * @package Spatial\Console\Commands
 */
class ConfigCacheCommand extends AbstractCommand
{
    public function getName(): string
    {
        return 'config:cache';
    }

    public function getDescription(): string
    {
        return 'Cache configuration for production';
    }

    public function execute(array $args, Application $app): int
    {
        $this->app = $app;

        $configDir = $this->getBasePath() . '/config';
        $cacheDir = $this->getBasePath() . '/var/cache';
        $cacheFile = "{$cacheDir}/config.cache.php";

        $this->output("Caching configuration...");

        if (!is_dir($configDir)) {
            $this->error("Config directory not found: {$configDir}");
            return 1;
        }

        $this->ensureDirectory($cacheDir);

        // Collect all configuration
        $config = $this->collectConfig($configDir);

        // Generate cache file
        $cacheContent = $this->generateCacheFile($config);

        if ($this->writeFile($cacheFile, $cacheContent)) {
            $this->success("Configuration cached: {$cacheFile}");
            $this->output("  Files cached: " . count($config));
            return 0;
        }

        $this->error("Failed to cache configuration");
        return 1;
    }

    private function collectConfig(string $dir): array
    {
        $config = [];

        // Process YAML files
        $yamlFiles = glob("{$dir}/*.yaml") + glob("{$dir}/**/*.yaml");
        
        foreach ($yamlFiles as $file) {
            $relativePath = str_replace($this->getBasePath() . '/', '', $file);
            $key = $this->pathToKey($file, $dir);
            
            try {
                if (class_exists('Symfony\\Component\\Yaml\\Yaml')) {
                    $config[$key] = \Symfony\Component\Yaml\Yaml::parseFile($file);
                } else {
                    $this->warning("Symfony YAML not available, skipping: {$relativePath}");
                }
            } catch (\Exception $e) {
                $this->warning("Failed to parse: {$relativePath}");
            }
        }

        // Process PHP config files
        $phpFiles = glob("{$dir}/*.php");
        
        foreach ($phpFiles as $file) {
            $key = $this->pathToKey($file, $dir);
            try {
                $config[$key] = require $file;
            } catch (\Exception $e) {
                $this->warning("Failed to load: " . basename($file));
            }
        }

        return $config;
    }

    private function pathToKey(string $file, string $baseDir): string
    {
        $relative = str_replace($baseDir . '/', '', $file);
        $relative = preg_replace('/\.(yaml|php)$/', '', $relative);
        return str_replace(['/', '\\'], '.', $relative);
    }

    private function generateCacheFile(array $config): string
    {
        $exported = var_export($config, true);
        
        return <<<PHP
<?php
/**
 * Configuration Cache
 * Generated: {$this->now()}
 * 
 * Do not edit this file manually.
 * Regenerate with: php spatial config:cache
 */

return {$exported};
PHP;
    }

    private function now(): string
    {
        return date('Y-m-d H:i:s');
    }
}
